# Generated by Django 6.0.3 on 2026-04-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0002_receipt_receiptitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
                ('mpesa_receipt', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_code', models.CharField(max_length=20, unique=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
            ],
        ),
    ]
